-- Run this entire file in Supabase SQL Editor.
-- Then create a Storage bucket named: ycloud

create table if not exists public.files (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  filename text not null,
  content_type text not null default 'application/octet-stream',
  latest_version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.versions (
  id bigint generated by default as identity primary key,
  file_id bigint not null references public.files(id) on delete cascade,
  version integer not null,
  size_bytes bigint not null,
  chunk_size integer not null default 5242880,
  total_chunks integer not null,
  checksum text,
  status text not null default 'uploading',
  created_at timestamptz not null default now(),
  unique(file_id, version)
);

create table if not exists public.chunks (
  id bigint generated by default as identity primary key,
  version_id bigint not null references public.versions(id) on delete cascade,
  chunk_index integer not null,
  size_bytes integer not null,
  checksum text not null,
  replica_a text not null,
  replica_b text not null,
  created_at timestamptz not null default now(),
  unique(version_id, chunk_index)
);

alter table public.files enable row level security;
alter table public.versions enable row level security;
alter table public.chunks enable row level security;

create policy "files owner read" on public.files for select using (auth.uid() = owner_id);
create policy "files owner insert" on public.files for insert with check (auth.uid() = owner_id);
create policy "files owner update" on public.files for update using (auth.uid() = owner_id);
create policy "files owner delete" on public.files for delete using (auth.uid() = owner_id);

create policy "versions owner read" on public.versions for select using (
  exists (select 1 from public.files f where f.id = file_id and f.owner_id = auth.uid())
);
create policy "versions owner insert" on public.versions for insert with check (
  exists (select 1 from public.files f where f.id = file_id and f.owner_id = auth.uid())
);
create policy "versions owner update" on public.versions for update using (
  exists (select 1 from public.files f where f.id = file_id and f.owner_id = auth.uid())
);
create policy "versions owner delete" on public.versions for delete using (
  exists (select 1 from public.files f where f.id = file_id and f.owner_id = auth.uid())
);

create policy "chunks owner read" on public.chunks for select using (
  exists (select 1 from public.versions v join public.files f on f.id=v.file_id where v.id=version_id and f.owner_id=auth.uid())
);
create policy "chunks owner insert" on public.chunks for insert with check (
  exists (select 1 from public.versions v join public.files f on f.id=v.file_id where v.id=version_id and f.owner_id=auth.uid())
);
create policy "chunks owner update" on public.chunks for update using (
  exists (select 1 from public.versions v join public.files f on f.id=v.file_id where v.id=version_id and f.owner_id=auth.uid())
);
create policy "chunks owner delete" on public.chunks for delete using (
  exists (select 1 from public.versions v join public.files f on f.id=v.file_id where v.id=version_id and f.owner_id=auth.uid())
);

-- Storage bucket. If the dashboard already created it, this statement is harmless.
insert into storage.buckets (id, name, public, file_size_limit)
values ('ycloud', 'ycloud', false, 52428800)
on conflict (id) do nothing;

create policy "ycloud upload own" on storage.objects for insert to authenticated
with check (bucket_id='ycloud' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "ycloud read own" on storage.objects for select to authenticated
using (bucket_id='ycloud' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "ycloud update own" on storage.objects for update to authenticated
using (bucket_id='ycloud' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "ycloud delete own" on storage.objects for delete to authenticated
using (bucket_id='ycloud' and (storage.foldername(name))[1] = auth.uid()::text);
